### ISSUE TITLE
ORA-04030 out of process memory on P_STACK.getCallStack

### ISSUE THREAD

**Issue by Sash0k** [Qualtagh/OracleDBUtils#6]
Hello, sometimes we're get out of memory with p_stack.getCallStack 
DB version: 11.2.0.4.0

```
ORA-04030: out of process memory when trying to allocate 215056 bytes (callheap,pp_src)
ORA-04030: out of process memory when trying to allocate 216080 bytes (PLS CGA hp,Static SQL string)
ORA-06512: on "SYS.DBMS_PREPROCESSOR", line 84
ORA-06512: on "SYS.DBMS_PREPROCESSOR", line 194
ORA-06512: on "APPS.P_STACK", line 137
ORA-06512: on "APPS.P_STACK", line 559
ORA-06512: on "APPS.UTL_CALL_STACK", line 50
```

it occurs in line 137:
`tPreprocessed := dbms_preprocessor.get_post_processed_source( tType, tOwner, tName );`

Could you help any ways to avoid/fix it?

**Comment by Qualtagh** [comment]
Hi,

does your source code really need post-processing (does it contain $if and $then)?
If no then perhaps this condition should be enhanced:

```
        select SOURCE_PREPROCESSOR
        into tSourceType
        from ALL_SOURCE
        where OWNER = tOwner
          and NAME = tName
          and TYPE = tType
          and LINE <= tLine
          and TEXT like '%$%'
          and rownum = 1;
```

It looks for a simple `$` in source. Maybe `$if` and `$then` are a better fit.

If your source code really needs post-processing then consider increasing memory limits. Honestly, I don't know how to do it but quick search shows some parameters to tweak, so it must be possible.

**Comment by Sash0k** [comment]
> It looks for a simple $ in source. Maybe $if and $then are a better fit.

maybe it would better to update in upstream? Seems it will be more optimal selection.
my variant is: `upper(TEXT) like '%$IF %'`

**Comment by Qualtagh** [comment]
> my variant is: upper(TEXT) like '%$IF %'

Yes, this is better. But `$IF` can appear at the end of the line.

> update in upstream

I'm not very familiar with git. Do you mean to make a change for everybody, in master tree? Certainly! I just want to ensure that it helps in your situation.

**Comment by Sash0k** [comment]
> But $IF can appear at the end of the line.

Thank you, that's my bad.

Yes, this patch will be helpful. Our code contains $ symbol, but not conditional compilation.
Our packages are about 16k lines of code, so it will be good optimization

**Comment by Qualtagh** [comment]
Committed. Please let me know if the issue persists.
https://github.com/Qualtagh/OracleDBUtils/commit/0513fe6b053b31e6c09ac6f86eb2064733ecf32d

**Comment by Sash0k** [comment]
Weekly test passed, thanks.
